### ISSUE TITLE
Clarify FERPA Exception in "Additional Terms of Use for Schools"

### ISSUE THREAD

**Issue by dccarroll** [Clever/policies#8]
In Section 1 of "Additional Terms of Use for Schools" we write:

> We provide the Services as an outsourced institutional function under FERPA 34 CFR Part 99.31(a)(1).

We should change this line to:

> We provide the Services under the school official exception under FERPA 34 CFR Part 99.31(a)(1).

**Comment by alsmola** [comment]
See https://github.com/Clever/policies/pull/9

**Comment by alsmola** [comment]
Merged https://github.com/Clever/policies/pull/9
